export { getCol } from './getCol'
export { getRow } from './getRow'
export { getSquare } from './getSquare'
export { removeValueFromCell } from './removeValueFromCell'
export { removeValueFromLines } from './removeValueFromLines'
export { removeValueFromSquares } from './removeValueFromSquares'
