export { clone } from './clone'
export { getCell } from './getCell'
export { removeSymmetricalIndexes } from './removeSymmetricalIndexes'
export { rotate } from './rotate'
export { shift } from './shift'
export { shuffle } from './shuffle'
export { switchColumns } from './switchColumns'
export { switchRows } from './switchRows'
